project:
  type: website
  resources:
    - assets/**

lang: fr
freeze: auto

website:
  title: "Les Types de LLM"
  description: "Chronologie & blog des architectures de LLM"
  favicon: assets/favicon.svg
  navbar:
    logo: assets/logo.svg
    right:
      - text: "Accueil"
        href: index.qmd
      - text: "Roadmap"
        href: roadmap/index.qmd
      - text: "Blog"
        href: blog/index.qmd
      - text: "À propos"
        href: about.qmd
      - text: "Contact"
        href: contact.qmd
  page-footer:
    left: "© 2025 — Marylène Henry"
    right:
      - text: "Fait avec Quarto"
        href: https://quarto.org
  site-url: https://maryleneh.github.io/Types_LLM/

format:
  html:
    theme:
      light: [cosmo, styles/theme_light.scss]
      dark:  [cosmo, styles/theme_dark.scss]
    css: styles/site.css
    toc: true
    smooth-scroll: true
    grid:
      body-width: 1000px
    code-copy: true
    highlight-style: a11y
    respect-user-color-scheme: true
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">

editor: visual
